spring:
  application:
    name: ecom-application
  h2:
    console:
      enabled: true  #This enables the Browser console
  datasource:
    url: jdbc:h2:mem:test # this will create in Memory DB with DB name test
  jpa:
    show-sql: true # to show sql query in the console logs
    hibernate:
      ddl-auto: create # to execute DDL statement i.e, CRUD operation. create will crate new table everytime when application starts or update the table schema.

management:
  endpoints:
    web:
      exposure:
        include: "*" # exposes all endpoints, not suitable for prod env
  endpoint:
    health:
      show-details: ALWAYS # default is NEVER
      #show-details: WHEN_AUTHORIZED # for authorized user
  info:
    env:
      enabled: true

info:
  app:
    name: ecom-application
    description: App built by me
    version: 1.0.0
